// Generated by schemas/generate_prisma_audio_bindings.py; do not edit.
// Schema source SHA-256: 55014f3629d92983ff7d3fcab8e6f740a793f6654912fac12d6469eb6d3a1fb0
export const PRISMA_AUDIO_METRIC_SCHEMA_SOURCE_SHA256 = "55014f3629d92983ff7d3fcab8e6f740a793f6654912fac12d6469eb6d3a1fb0" as const;
export const PRISMA_AUDIO_METRIC_SCHEMA_VERSION = "1" as const;
export type PrismaAudioLayer = "provider" | "backend" | "browser";
export const STATUS = ["success", "error", "cancel"] as const;
export type PrismaAudioMetricStatus = typeof STATUS[number];
export const CODE = ["provider-failure", "backend-failure", "browser-failure", "cancelled", "invalid-format", "unknown"] as const;
export type PrismaAudioMetricCode = typeof CODE[number];
export const TRANSPORT = ["progressive", "buffer-before-playback"] as const;
export type PrismaAudioMetricTransport = typeof TRANSPORT[number];
export const ERROR_CODE = ["audio-failure"] as const;
export type PrismaAudioMetricErrorCode = typeof ERROR_CODE[number];
export type PrismaAudioMetricPayload =
    | { record_type: 'request-start'; payload: Record<string, never> }
    | { record_type: 'first-readable-audio'; payload: {
        elapsed_ms: number;
        pcm_bytes: number;
    } }
    | { record_type: 'buffering-complete'; payload: {
        elapsed_ms: number;
        pcm_bytes: number;
        pcm_duration_seconds: number | null;
    } }
    | { record_type: 'eof'; payload: {
        elapsed_ms: number;
        transport: PrismaAudioMetricTransport;
        pcm_bytes: number;
        pcm_duration_seconds: number | null;
    } }
    | { record_type: 'canonical-decode'; payload: {
        elapsed_ms: number;
        transport: PrismaAudioMetricTransport;
        pcm_bytes: number;
        pcm_duration_seconds: number | null;
    } }
    | { record_type: 'playback-started'; payload: {
        elapsed_ms: number;
        transport: PrismaAudioMetricTransport;
        pcm_bytes: number;
        pcm_duration_seconds: number | null;
        underflow_count: number;
    } }
    | { record_type: 'playback-ended'; payload: {
        elapsed_ms: number;
        transport: PrismaAudioMetricTransport;
        pcm_bytes: number;
        pcm_duration_seconds: number | null;
        underflow_count: number;
    } }
    | { record_type: 'underflow'; payload: {
        underflow_count: number;
    } }
    | { record_type: 'error'; payload: {
        code?: PrismaAudioMetricCode;
        status?: PrismaAudioMetricStatus;
        elapsed_ms: number;
        error_code: PrismaAudioMetricErrorCode;
    } }
    | { record_type: 'cancel'; payload: {
        code?: PrismaAudioMetricCode;
        status?: PrismaAudioMetricStatus;
        elapsed_ms: number;
    } };
export type PrismaAudioMetric = {
    schema_version: typeof PRISMA_AUDIO_METRIC_SCHEMA_VERSION;
    run_id: string;
    layer: "browser";
    sequence: number;
    monotonic_ms: number;
    elapsed_ms: number;
} & PrismaAudioMetricPayload;

const BROWSER_RECORD_TYPES = ["request-start", "first-readable-audio", "buffering-complete", "eof", "canonical-decode", "playback-started", "playback-ended", "underflow", "error", "cancel"] as const;
const PAYLOAD_FIELDS: Record<string, readonly string[]> = {"dispatch":[],"completion":["status"],"receipt":[],"dsp":["sample_count"],"yield":["sample_count"],"finalization":["status","sample_count","duration_ms"],"request-start":[],"first-readable-audio":["elapsed_ms","pcm_bytes"],"buffering-complete":["elapsed_ms","pcm_bytes","pcm_duration_seconds"],"eof":["elapsed_ms","transport","pcm_bytes","pcm_duration_seconds"],"canonical-decode":["elapsed_ms","transport","pcm_bytes","pcm_duration_seconds"],"playback-started":["elapsed_ms","transport","pcm_bytes","pcm_duration_seconds","underflow_count"],"playback-ended":["elapsed_ms","transport","pcm_bytes","pcm_duration_seconds","underflow_count"],"underflow":["underflow_count"],"error":["code","status","elapsed_ms","error_code"],"cancel":["code","status","elapsed_ms"]};
const REQUIRED_PAYLOAD_FIELDS: Record<string, readonly string[]> = {"request-start":[],"first-readable-audio":["elapsed_ms","pcm_bytes"],"buffering-complete":["elapsed_ms","pcm_bytes","pcm_duration_seconds"],"eof":["elapsed_ms","transport","pcm_bytes","pcm_duration_seconds"],"canonical-decode":["elapsed_ms","transport","pcm_bytes","pcm_duration_seconds"],"playback-started":["elapsed_ms","transport","pcm_bytes","pcm_duration_seconds","underflow_count"],"playback-ended":["elapsed_ms","transport","pcm_bytes","pcm_duration_seconds","underflow_count"],"underflow":["underflow_count"],"error":["elapsed_ms","error_code"],"cancel":["elapsed_ms"]};
const PAYLOAD_KINDS: Record<string, string> = {"status":"enum","code":"enum","sample_count":"nonnegative-integer","duration_ms":"nonnegative-number","elapsed_ms":"nonnegative-number","transport":"enum","pcm_bytes":"nonnegative-number","pcm_duration_seconds":"nullable-nonnegative-number","underflow_count":"nonnegative-integer","error_code":"enum"};
const PAYLOAD_ENUMS: Record<string, readonly string[]> = {"status":["success","error","cancel"],"code":["provider-failure","backend-failure","browser-failure","cancelled","invalid-format","unknown"],"transport":["progressive","buffer-before-playback"],"error_code":["audio-failure"]};

function isRecord(value: unknown): value is Record<string, unknown> {
    return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isNonNegativeFinite(value: unknown): value is number {
    return typeof value === "number" && Number.isFinite(value) && value >= 0;
}

function isPayloadValue(key: string, value: unknown): boolean {
    const kind = PAYLOAD_KINDS[key];
    if (kind === "enum") return typeof value === "string" && PAYLOAD_ENUMS[key]?.includes(value) === true;
    if (kind === "nonnegative-integer") return typeof value === "number" && Number.isSafeInteger(value) && value >= 0;
    if (kind === "nullable-nonnegative-number") return value === null || isNonNegativeFinite(value);
    return kind === "nonnegative-number" && isNonNegativeFinite(value);
}

function isBrowserMetric(value: Record<string, unknown>): boolean {
    if (!BROWSER_RECORD_TYPES.includes(value.record_type as typeof BROWSER_RECORD_TYPES[number])) return false;
    if (!isRecord(value.payload)) return false;
    const fields = PAYLOAD_FIELDS[value.record_type as string] ?? [];
    const required = REQUIRED_PAYLOAD_FIELDS[value.record_type as string] ?? [];
    const payload = value.payload;
    return Object.keys(payload).every((key) => fields.includes(key))
        && required.every((key) => Object.prototype.hasOwnProperty.call(payload, key))
        && Object.entries(payload).every(([key, item]) => isPayloadValue(key, item));
}

export function isPrismaAudioMetric(value: unknown): value is PrismaAudioMetric {
    if (!isRecord(value)
        || value.schema_version !== PRISMA_AUDIO_METRIC_SCHEMA_VERSION
        || value.layer !== "browser"
        || typeof value.run_id !== "string"
        || !/^prisma-[0-9a-f]{16,64}$/.test(value.run_id)
        || !isNonNegativeFinite(value.sequence)
        || !Number.isSafeInteger(value.sequence)
        || !isNonNegativeFinite(value.monotonic_ms)
        || !isNonNegativeFinite(value.elapsed_ms)) return false;
    const baseKeys = ["schema_version", "run_id", "layer", "record_type", "sequence", "monotonic_ms", "elapsed_ms", "payload"];
    return Object.keys(value).every((key) => baseKeys.includes(key)) && isBrowserMetric(value);
}

export function parsePrismaAudioMetric(value: unknown): PrismaAudioMetric {
    if (!isPrismaAudioMetric(value)) throw new Error("Prisma audio metric violates the browser allowlist");
    return value;
}

export function validatePrismaAudioMetricSequence(values: readonly unknown[]): PrismaAudioMetric[] {
    let previousMonotonic = -Infinity;
    let previousElapsed = -Infinity;
    return values.map((value) => {
        const metric = parsePrismaAudioMetric(value);
        if (metric.monotonic_ms < previousMonotonic || metric.elapsed_ms < previousElapsed) throw new Error("Prisma audio metric timestamps must be monotonic");
        previousMonotonic = metric.monotonic_ms;
        previousElapsed = metric.elapsed_ms;
        return metric;
    });
}
