import { describe, expect, it } from 'vitest';
import indexHtml from '../../index.html?raw';
import shaderDocs from '../../../docs/SHADER_BACKGROUND.md?raw';

const shieldMarkupMatch = indexHtml.match(/<div id="hmi-shield"[\s\S]*?<\/div>/);
const shieldMarkup = shieldMarkupMatch?.[0] ?? '';

describe('boot reload shield static assets', () => {
    it('defines pre-React shield markup with fixed typewriter message, bottom trail, and fallback font', () => {
        expect(shieldMarkup).toContain('<div id="hmi-shield" data-hmi-shield-state="visible" role="status" aria-live="polite">');
        expect(shieldMarkup).toContain('data-hmi-shield-typewriter');
        expect(shieldMarkup).toContain('data-hmi-shield-typed');
        expect(shieldMarkup).toContain('data-hmi-shield-caret');
        expect(shieldMarkup).toContain('ACTUALIZANDO DATOS');
        expect((shieldMarkup.match(/ACTUALIZANDO DATOS/g) ?? [])).toHaveLength(1);
        expect(shieldMarkup).not.toContain('ACTUALIZANDO DATOS...');
        expect(shieldMarkup).not.toContain('Sistema inicializando…');
        expect(shieldMarkup).not.toContain('<strong>');
        expect(shieldMarkup).not.toContain('hmi-shield-status');
        expect(shieldMarkup).not.toContain('Interfaz Laboratorio');
        expect(shieldMarkup).not.toContain('HMI');
        expect(shieldMarkup).not.toContain('data-hmi-shield-label');
        expect(shieldMarkup).toContain('data-hmi-shield-cursor-loader');
        expect(shieldMarkup).toContain('data-hmi-shield-trail="g5"');
        expect(shieldMarkup).toContain('data-hmi-shield-trail="g4"');
        expect(shieldMarkup).toContain('data-hmi-shield-trail="g3"');
        expect(shieldMarkup).toContain('data-hmi-shield-trail="g2"');
        expect(shieldMarkup).toContain('data-hmi-shield-trail="g1"');
        expect(shieldMarkup).toContain('data-hmi-shield-trail="head"');
        expect(indexHtml).toContain('--hmi-shield-ink: currentColor;');
        expect(indexHtml).toContain('--hmi-shield-short-shell-width: 8ch;');
        expect(indexHtml).toContain('--hmi-shield-short-typing-duration: 320ms;');
        expect(indexHtml).toContain('--hmi-shield-short-typing-delay: 300ms;');
        expect(indexHtml).toContain('--hmi-shield-short-caret-blink-delay: 620ms;');
        expect(indexHtml).toContain('background-color: var(--color-industrial-bg, #05070a);');
        expect(indexHtml).toContain('font-family: Consolas, monospace;');
        expect(indexHtml).toContain('opacity: 1;');
        expect(indexHtml).toContain('visibility: visible;');
        expect(indexHtml).toContain('pointer-events: none;');
        expect(indexHtml).toContain('width: 18ch;');
        expect(indexHtml).toContain('justify-content: center;');
        expect(indexHtml).toContain('text-align: left;');
        expect(indexHtml).toContain('letter-spacing: 0;');
        expect(indexHtml).toContain('animation: typing 0.8s steps(1) 0.6s forwards;');
        expect(indexHtml).toContain('caret-idle 0.6s steps(1) 0s 1,');
        expect(indexHtml).toContain('caret-move 0.8s steps(1) 0.6s forwards,');
        expect(indexHtml).toContain('caret-blink 0.6s steps(1) 1.4s 1 forwards;');
        expect(indexHtml).toContain('@keyframes typing');
        expect(indexHtml).toContain('@keyframes caret-move');
        expect(indexHtml).toContain('@keyframes short-typing');
        expect(indexHtml).toContain('@keyframes short-caret-move');
        expect(indexHtml).toContain('@keyframes short-caret-blink');
        expect(indexHtml).toContain('@keyframes short-caret-idle');
        expect(indexHtml).toContain('@keyframes caret-blink');
        expect(indexHtml).toContain('@keyframes caret-idle');
        expect(indexHtml).toContain('@keyframes walk');
        expect(indexHtml).toContain('width: 10ch;');
        expect(indexHtml).toContain('letter-spacing: 0.05em;');
        expect(indexHtml).toContain('animation: walk 1.8s steps(1) 1.7s infinite;');
        expect(indexHtml).toContain('animation: walk 1.8s steps(1) 2.2s infinite;');
        expect(indexHtml).toContain('--hmi-shield-trail-color: #f0f0f0;');
        expect(indexHtml).toContain('--hmi-shield-trail-color: #898989;');
        expect(indexHtml).toContain('--hmi-shield-trail-color: #5b5b5b;');
        expect(indexHtml).toContain('--hmi-shield-trail-color: #3d3d3d;');
        expect(indexHtml).toContain('--hmi-shield-trail-color: #282828;');
        expect(indexHtml).toContain('--hmi-shield-trail-color: #1a1a1a;');
        expect(indexHtml).toContain('content: "_         ";');
        expect(indexHtml).toContain('content: "         _";');
        expect(indexHtml).toContain('7% { width: 1ch; }');
        expect(indexHtml).toContain('40% { width: 8ch; }');
        expect(indexHtml).toContain('72% { width: 13ch; }');
        expect(indexHtml).toContain('80% { width: 14ch; }');
        expect(indexHtml).toContain('7% { left: 1ch; }');
        expect(indexHtml).toContain('40% { left: 8ch; }');
        expect(indexHtml).toContain('72% { left: 13ch; }');
        expect(indexHtml).toContain('80% { left: 14ch; }');
        expect(indexHtml).toContain('17.5% { width: 1ch; }');
        expect(indexHtml).toContain('80% { width: 7ch; }');
        expect(indexHtml).toContain('100% { width: 8ch; }');
        expect(indexHtml).toContain('17.5% { left: 1ch; }');
        expect(indexHtml).toContain('80% { left: 7ch; }');
        expect(indexHtml).toContain('100% { left: 8ch; }');
        expect(indexHtml).toContain('[data-hmi-shield-short-shell]');
        expect(indexHtml).toContain('[data-hmi-shield-short-typewriter]');
        expect(indexHtml).toContain('[data-hmi-shield-short-typed]');
        expect(indexHtml).toContain('[data-hmi-shield-short-caret]');
        expect(indexHtml).not.toContain('#hmi-shield.hmi-shield--profile-short [data-hmi-shield-typed]');
        expect(indexHtml).not.toContain('#hmi-shield.hmi-shield--profile-short [data-hmi-shield-caret]');
        expect(indexHtml).toContain('@media (prefers-reduced-motion: reduce)');
        expect(indexHtml).toContain('[data-hmi-shield-typed]');
        expect(indexHtml).toContain('[data-hmi-shield-caret]');
        expect(indexHtml).toContain('[data-hmi-shield-short-typed]');
        expect(indexHtml).toContain('[data-hmi-shield-short-caret]');
        expect(indexHtml).toContain('animation: none !important;');
        expect(shieldMarkup).not.toContain('data-hmi-shield-state="visible" data-hmi-shield-variant="segments" role="status" aria-live="polite" aria-hidden="true"');
        expect(indexHtml).not.toContain('inert');
    });

    it('documents the static shield hidden-state contract and keyboard reload limitations', () => {
        expect(indexHtml).toContain('#hmi-shield[data-hmi-shield-state="hidden"]');
        expect(indexHtml).toContain('#hmi-shield.hmi-shield--hidden');
        expect(indexHtml).toContain('font-size: 0.875rem;');
        expect(indexHtml).toContain('letter-spacing: 0.08em;');
        expect(indexHtml).toContain('font: inherit;');
        expect(indexHtml).toContain('color: var(--color-industrial-bg, #05070a);');
        expect(indexHtml).toContain('width: min(18ch, 100%);');
        expect(indexHtml).toContain('max-width: 100%;');
        expect(indexHtml).toContain('align-items: center;');
        expect(indexHtml).not.toContain('translate');
        expect(indexHtml).not.toContain('scaleY');
        expect(indexHtml).not.toContain('scaleX');
        expect(shaderDocs).toContain('ACTUALIZANDO DATOS');
        expect(shaderDocs).toContain('Toolbar / browser chrome reload');
        expect(shaderDocs).toContain('no se puede interceptar desde JavaScript de página');
        expect(shaderDocs).toContain('location.reload()');
        expect(shaderDocs).toContain('no preserva hard-reload cache bypass');
        expect(shaderDocs).toContain('estado oscuro y legible');
    });
});
