"""Generate the checked Python and TypeScript projections for the Prisma audio schema."""
import argparse
import hashlib
import json
from pathlib import Path


# Every target is anchored on this file's own location, so the generator behaves
# identically regardless of the working directory it is invoked from.
REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
SCHEMA = Path(__file__).resolve().with_name("prisma-audio-record.v1.schema.json")
PYTHON_PROJECTION = REPOSITORY_ROOT / "services" / "prisma-runtime" / "src" / "prisma_runtime" / "audio_record_types.py"
TYPESCRIPT = REPOSITORY_ROOT / "hmi-app" / "src" / "domain" / "prismaAudioMetric.generated.ts"


def schema_data(path=SCHEMA):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def source_hash(path=SCHEMA):
    content = Path(path).read_bytes().replace(b"\r\n", b"\n").replace(b"\r", b"\n")
    return hashlib.sha256(content).hexdigest()


def render_python(data, digest):
    layers = data["x-record-types"]
    payload_keys = data["x-payload-fields"]
    required_fields = data["x-required-payload-fields"]
    payload_kinds = data["x-payload-kinds"]
    payload_enums = data["x-payload-enums"]
    return f'''# Generated by schemas/generate_prisma_audio_bindings.py; do not edit.
import math
import re

SCHEMA_SOURCE_SHA256 = "{digest}"
SCHEMA_VERSION = "1"
ALLOWED_RECORD_TYPES = {layers!r}
TERMINAL_STATUSES = {{"success", "error", "cancel"}}
PAYLOAD_KEYS = {payload_keys!r}
REQUIRED_PAYLOAD_FIELDS = {required_fields!r}
PAYLOAD_KINDS = {payload_kinds!r}
PAYLOAD_VALUES = {payload_enums!r}

def _is_nonnegative_number(value):
    return isinstance(value, (int, float)) and not isinstance(value, bool) and value >= 0 and (not isinstance(value, float) or math.isfinite(value))

def make_record(run_id, layer, record_type, sequence, monotonic_ms, elapsed_ms, payload):
    if not isinstance(run_id, str) or re.fullmatch(r"prisma-[0-9a-f]{{16,64}}", run_id) is None: raise ValueError("opaque run_id required")
    if layer not in ALLOWED_RECORD_TYPES or record_type not in ALLOWED_RECORD_TYPES[layer]: raise ValueError("record type is not allowed for layer")
    if not isinstance(sequence, int) or isinstance(sequence, bool) or sequence < 0: raise ValueError("sequence must be a non-negative integer")
    if not _is_nonnegative_number(monotonic_ms): raise ValueError("monotonic_ms must be finite and non-negative")
    if not _is_nonnegative_number(elapsed_ms): raise ValueError("elapsed_ms must be finite and non-negative")
    if not isinstance(payload, dict) or not set(payload).issubset(PAYLOAD_KEYS[record_type]): raise ValueError("payload field is not allowlisted")
    if not set(REQUIRED_PAYLOAD_FIELDS.get(record_type, ())).issubset(payload): raise ValueError("required payload field is missing")
    for key, value in payload.items():
        kind = PAYLOAD_KINDS.get(key)
        if kind == "enum" and (not isinstance(value, str) or value not in PAYLOAD_VALUES[key]): raise ValueError("payload value is not typed")
        if kind == "nonnegative-integer" and (not isinstance(value, int) or isinstance(value, bool) or value < 0): raise ValueError("count must be a non-negative integer")
        if kind == "nonnegative-number" and not _is_nonnegative_number(value): raise ValueError("value must be finite and non-negative")
        if kind == "nullable-nonnegative-number" and value is not None and not _is_nonnegative_number(value): raise ValueError("value must be finite and non-negative or null")
    return {{"schema_version": SCHEMA_VERSION, "run_id": run_id, "layer": layer, "record_type": record_type, "sequence": sequence, "monotonic_ms": float(monotonic_ms), "elapsed_ms": float(elapsed_ms), "payload": dict(payload)}}

class RecordStream:
    def __init__(self, run_id): self.run_id, self.sequence, self.last_monotonic_ms, self.last_elapsed_ms = run_id, 0, -1.0, -1.0
    def emit(self, layer, record_type, monotonic_ms, elapsed_ms, payload):
        if monotonic_ms < self.last_monotonic_ms or elapsed_ms < self.last_elapsed_ms: raise ValueError("clock moved backwards")
        item = make_record(self.run_id, layer, record_type, self.sequence, monotonic_ms, elapsed_ms, payload)
        self.sequence += 1; self.last_monotonic_ms, self.last_elapsed_ms = monotonic_ms, elapsed_ms
        return item
'''


def render_typescript(data, digest):
    browser_types = data["x-record-types"]["browser"]
    payload_fields = data["x-payload-fields"]
    required_fields = data["x-required-payload-fields"]
    kinds = data["x-payload-kinds"]
    enums = data["x-payload-enums"]
    type_names = {
        "enum": "string",
        "nonnegative-integer": "number",
        "nonnegative-number": "number",
        "nullable-nonnegative-number": "number | null",
    }
    enum_types = {
        field: "PrismaAudioMetric" + "".join(part.title() for part in field.split("_"))
        for field in enums
    }
    type_names.update({field: enum_types[field] for field in enums})
    enum_exports = "\n".join(
        f"export const {name.upper()} = {json.dumps(values)} as const;\n"
        f"export type {enum_types[name]} = typeof {name.upper()}[number];"
        for name, values in enums.items()
    )
    members = []
    for record_type in browser_types:
        fields = []
        for field in payload_fields[record_type]:
            optional = "" if field in required_fields.get(record_type, []) else "?"
            field_type = enum_types.get(field, type_names[kinds[field]])
            fields.append(f"        {field}{optional}: {field_type};")
        payload = "Record<string, never>" if not fields else "{\n" + "\n".join(fields) + "\n    }"
        members.append(f"    | {{ record_type: {record_type!r}; payload: {payload} }}")
    return f'''// Generated by schemas/generate_prisma_audio_bindings.py; do not edit.
// Schema source SHA-256: {digest}
export const PRISMA_AUDIO_METRIC_SCHEMA_SOURCE_SHA256 = "{digest}" as const;
export const PRISMA_AUDIO_METRIC_SCHEMA_VERSION = "1" as const;
export type PrismaAudioLayer = "provider" | "backend" | "browser";
{enum_exports}
export type PrismaAudioMetricPayload =
{chr(10).join(members)};
export type PrismaAudioMetric = {{
    schema_version: typeof PRISMA_AUDIO_METRIC_SCHEMA_VERSION;
    run_id: string;
    layer: "browser";
    sequence: number;
    monotonic_ms: number;
    elapsed_ms: number;
}} & PrismaAudioMetricPayload;

const BROWSER_RECORD_TYPES = {json.dumps(browser_types)} as const;
const PAYLOAD_FIELDS: Record<string, readonly string[]> = {json.dumps({key: value for key, value in payload_fields.items()}, separators=(',', ':'))};
const REQUIRED_PAYLOAD_FIELDS: Record<string, readonly string[]> = {json.dumps(required_fields, separators=(',', ':'))};
const PAYLOAD_KINDS: Record<string, string> = {json.dumps(kinds, separators=(',', ':'))};
const PAYLOAD_ENUMS: Record<string, readonly string[]> = {json.dumps(enums, separators=(',', ':'))};

function isRecord(value: unknown): value is Record<string, unknown> {{
    return typeof value === "object" && value !== null && !Array.isArray(value);
}}

function isNonNegativeFinite(value: unknown): value is number {{
    return typeof value === "number" && Number.isFinite(value) && value >= 0;
}}

function isPayloadValue(key: string, value: unknown): boolean {{
    const kind = PAYLOAD_KINDS[key];
    if (kind === "enum") return typeof value === "string" && PAYLOAD_ENUMS[key]?.includes(value) === true;
    if (kind === "nonnegative-integer") return typeof value === "number" && Number.isSafeInteger(value) && value >= 0;
    if (kind === "nullable-nonnegative-number") return value === null || isNonNegativeFinite(value);
    return kind === "nonnegative-number" && isNonNegativeFinite(value);
}}

function isBrowserMetric(value: Record<string, unknown>): boolean {{
    if (!BROWSER_RECORD_TYPES.includes(value.record_type as typeof BROWSER_RECORD_TYPES[number])) return false;
    if (!isRecord(value.payload)) return false;
    const fields = PAYLOAD_FIELDS[value.record_type as string] ?? [];
    const required = REQUIRED_PAYLOAD_FIELDS[value.record_type as string] ?? [];
    const payload = value.payload;
    return Object.keys(payload).every((key) => fields.includes(key))
        && required.every((key) => Object.prototype.hasOwnProperty.call(payload, key))
        && Object.entries(payload).every(([key, item]) => isPayloadValue(key, item));
}}

export function isPrismaAudioMetric(value: unknown): value is PrismaAudioMetric {{
    if (!isRecord(value)
        || value.schema_version !== PRISMA_AUDIO_METRIC_SCHEMA_VERSION
        || value.layer !== "browser"
        || typeof value.run_id !== "string"
        || !/^prisma-[0-9a-f]{{16,64}}$/.test(value.run_id)
        || !isNonNegativeFinite(value.sequence)
        || !Number.isSafeInteger(value.sequence)
        || !isNonNegativeFinite(value.monotonic_ms)
        || !isNonNegativeFinite(value.elapsed_ms)) return false;
    const baseKeys = ["schema_version", "run_id", "layer", "record_type", "sequence", "monotonic_ms", "elapsed_ms", "payload"];
    return Object.keys(value).every((key) => baseKeys.includes(key)) && isBrowserMetric(value);
}}

export function parsePrismaAudioMetric(value: unknown): PrismaAudioMetric {{
    if (!isPrismaAudioMetric(value)) throw new Error("Prisma audio metric violates the browser allowlist");
    return value;
}}

export function validatePrismaAudioMetricSequence(values: readonly unknown[]): PrismaAudioMetric[] {{
    let previousMonotonic = -Infinity;
    let previousElapsed = -Infinity;
    return values.map((value) => {{
        const metric = parsePrismaAudioMetric(value);
        if (metric.monotonic_ms < previousMonotonic || metric.elapsed_ms < previousElapsed) throw new Error("Prisma audio metric timestamps must be monotonic");
        previousMonotonic = metric.monotonic_ms;
        previousElapsed = metric.elapsed_ms;
        return metric;
    }});
}}
'''


def generate(schema_path=SCHEMA, output=PYTHON_PROJECTION, typescript_output=TYPESCRIPT):
    data = schema_data(schema_path)
    digest = source_hash(schema_path)
    with Path(output).open("w", encoding="utf-8", newline="\n") as python_file:
        python_file.write(render_python(data, digest))
    with Path(typescript_output).open("w", encoding="utf-8", newline="\n") as typescript_file:
        typescript_file.write(render_typescript(data, digest))


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--schema", type=Path, default=SCHEMA)
    parser.add_argument("--output", type=Path, default=PYTHON_PROJECTION)
    parser.add_argument("--typescript-output", type=Path, default=TYPESCRIPT)
    args = parser.parse_args()
    generate(args.schema, args.output, args.typescript_output)
